const Common = require('@sixten/asteria-common');

module.exports = Common.Utils.Mapper([
	{ src: 'invoiceType', dest: 'type', default: 'invoice', required: true },
	{ src: 'canceled', dest: 'canceled', default: false, type: 'boolean' },
	{ src: 'invoiceNumber', dest: 'meta.invoiceNumber', required: true },
	{ src: 'termsOfPayment', dest: 'meta.termsOfPayment', default: '30' },
	{ src: 'sent', dest: 'dates.invoiceSent', type: 'date' },
	{ src: 'due', dest: 'dates.invoiceDue', type: 'date' },
	{ src: 'tax', dest: 'sums.tax', type: 'float' },
	{ src: 'total', dest: 'sums.invoiceTotal', type: 'float', required: true },
	{ src: 'currency', dest: 'sums.currency', required: true },
	{ src: 'credits', dest: 'credits[0]' },
	{ src: 'contact internal name', dest: 'contact.internal.name' },
	{ src: 'contact internal email', dest: 'contact.internal.email' },
	{ src: 'contact internal phone', dest: 'contact.internal.phone' },
	{ src: 'contact name', dest: 'contact.general.name' },
	{ src: 'contact email', dest: 'contact.general.email' },
	{ src: 'contact street', dest: 'contact.general.street' },
	{ src: 'contact street 2', dest: 'contact.general.street2' },
	{ src: 'contact city', dest: 'contact.general.city' },
	{ src: 'contact zipcode', dest: 'contact.general.zipcode' },
	{ src: 'contact phone', dest: 'contact.general.phone' },
	{ src: 'contact country', dest: 'contact.general.country' },
	{ src: 'shipping name', dest: 'contact.shipping.name' },
	{ src: 'shipping email', dest: 'contact.shipping.email' },
	{ src: 'shipping street', dest: 'contact.shipping.street' },
	{ src: 'shipping street 2', dest: 'contact.shipping.street2' },
	{ src: 'shipping city', dest: 'contact.shipping.city' },
	{ src: 'shipping zipcode', dest: 'contact.shipping.zipcode' },
	{ src: 'shipping phone', dest: 'contact.shipping.phone' },
	{ src: 'shipping country', dest: 'contact.shipping.country' },
]);
